# Create the service by executing
# $ kubectl apply -f k8s/services/api-service-lb.yaml

kind: Service
apiVersion: v1
metadata:
  name: rest-api-swagger
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 10010
    protocol: TCP
  selector:
    app: rest-api-swagger
